In [1]:
!pip install underthesea
!pip install vietnam-number
!pip install dask
!git clone https://github.com/stopwords/vietnamese-stopwords
!pip -q install pandarallel

Collecting underthesea
  Downloading underthesea-6.8.4-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: Click>=6.0 in /usr/local/lib/python3.11/dist-packages (from underthesea) (8.2.1)
Collecting python-crfsuite>=0.9.6 (from underthesea)
  Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (from underthesea) (3.9.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from underthesea) (4.67.1)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from underthesea) (2.32.4)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from underthesea) (1.5.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from underthesea) (1.2.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from underthesea) (6.0.2)
Collecting underthesea-core==1.0.4 (from underthesea)
  Downloading underthesea_core-1.0.4-cp311-cp311-manylinux2010_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk->underthesea) (2024.11.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->underthesea) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->underthesea) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->underthesea) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->underthesea) (2025.6.15)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->underthesea) (1.26.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->underthesea) (1.15.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->underthesea) (3.6.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.17.3->scikit-learn->underthesea) (2.4.1)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn->underthesea) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.17.3->scikit-learn->underthesea) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.17.3->scikit-learn->underthesea) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.17.3->scikit-learn->underthesea) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.17.3->scikit-learn->underthesea) (2024.2.0)
Downloading underthesea-6.8.4-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 28.7 MB/s eta 0:00:0000:0100:01m
Downloading underthesea_core-1.0.4-cp311-cp311-manylinux2010_x86_64.whl (657 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 657.8/657.8 kB 39.2 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.11-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 49.4 MB/s eta 0:00:00
Installing collected packages: underthesea-core, python-crfsuite, underthesea
Successfully installed python-crfsuite-0.9.11 underthesea-6.8.4 underthesea-core-1.0.4
Collecting vietnam-number
  Downloading vietnam_number-1.0.5-py3-none-any.whl.metadata (11 kB)
Downloading vietnam_number-1.0.5-py3-none-any.whl (22 kB)
Installing collected packages: vietnam-number
Successfully installed vietnam-number-1.0.5
Requirement already satisfied: dask in /usr/local/lib/python3.11/dist-packages (2024.12.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask) (8.2.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from dask) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/dist-packages (from dask) (2025.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from dask) (25.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from dask) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask) (1.0.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in /usr/local/lib/python3.11/dist-packages (from dask) (8.7.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib_metadata>=4.13.0->dask) (3.23.0)
Requirement already satisfied: locket in /usr/local/lib/python3.11/dist-packages (from partd>=1.4.0->dask) (1.0.0)
Cloning into 'vietnamese-stopwords'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 95 (delta 3), reused 0 (delta 0), pack-reused 81 (from 1)
Receiving objects: 100% (95/95), 40.25 KiB | 8.05 MiB/s, done.
Resolving deltas: 100% (31/31), done.
  Preparing metadata (setup.py) ... done
  Building wheel for pandarallel (setup.py) ... done

In [60]:
import csv
import json
import math
import os
import random
import re
import unicodedata
import zipfile
from collections import Counter, defaultdict
from functools import partial
from multiprocessing import cpu_count
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

from underthesea import text_normalize, word_tokenize
from vietnam_number import n2w

import dask.bag as db
from dask import dataframe as dd
from dask.diagnostics import ProgressBar
from dask.multiprocessing import get

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader, Dataset

from pandarallel import pandarallel
from tqdm import tqdm
import matplotlib.pyplot as plt
from tqdm import tqdm
from contextlib import nullcontext

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("iambestfeeder/10000-vietnamese-books")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/10000-vietnamese-books

In [4]:
def load_books(data_directory):
    texts = []
    titles = []
    authors = []

    files = os.listdir(data_directory)

    for file_name in files:
        file_path = os.path.join(data_directory, file_name)

        with open(file_path, 'r', encoding='utf-8') as file:
            content = file.read().strip()

            texts.append(content)

            title = file_name.replace('.txt', '').split('-')[:-1]
            author=file_name.replace('.txt', '').split('-')[-1]
            titles.append(title)
            authors.append(author)


    return pd.DataFrame({'Titles': titles, 'Texts': texts,'Authors':authors})

In [5]:
data_directory = '/kaggle/input/10000-vietnamese-books/output'
dataset = load_books(data_directory)
dataset.head()

,Titles,Texts,Authors
0,[Nhà ảo thuật ],Mạc Can\nNhà ảo thuật\nCó một cậu bé muốn học ...,Mạc Can
1,[Ra đi ],Trần Chi Liên\nRa đi\nTặng người đồng cảnh tươ...,Trần Chi Liên
2,[Đường về ],"Vũ Thư Nguyên\nĐường về\nVừa ra khỏi xa lộ 66,...",Vũ Thư Nguyên
3,[Bốn Thằng Buồn ],Phi Va\nBốn Thằng Buồn\n&quot;Bốn người lính b...,Phi Va
4,[Chiếc Lexus và cây Ô liu ],Thomas L. Friedman\nChiếc Lexus và cây Ô liu\n...,Thomas L. Friedman

In [6]:
dataset.shape

(10415, 3)

# Split data

In [7]:
class DataSplitter:
    def __init__(self, train_ratio = 0.7, val_ratio = 0.1, seed = 42, shuffle = True):
        self.train_ratio = train_ratio
        self.val_ratio   = val_ratio
        self.seed        = seed
        self.shuffle     = shuffle
    
    def split(self, data: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        df = data.copy()
        
        if self.shuffle:
            df = df.sample(frac=1, random_state=self.seed).reset_index(drop=True)

        n = len(df)
        n_train = int(n * self.train_ratio)
        n_val   = int(n * self.val_ratio)

        train = df.iloc[:n_train]
        val   = df.iloc[n_train:n_train+n_val]
        test  = df.iloc[n_train+n_val:]
        return train, val, test

In [8]:
splitter = DataSplitter(train_ratio=0.7, val_ratio=0.1, seed=42, shuffle=True)

train_df, val_df, test_df = splitter.split(dataset)

print(len(train_df), len(val_df), len(test_df))

7290 1041 2084

In [9]:
train_df

,Titles,Texts,Authors
0,[Sanh Rớt ],"Hòa Đa\nSanh Rớt\nThời gian gặp lại vợ con, sa...",Hòa Đa
1,[Không Khóc ở California ],Nguyễn Huy Thiệp\nKhông Khóc ở California\nAnh...,Nguyễn Huy Thiệp
2,[Võ Lâm Tình Sử ],Đông Tà\nVõ Lâm Tình Sử\nHồi 1\nHại Thân Vì Bữ...,Đông Tà
3,[Sherlock Holmes trở về ],Sir ARTHUR CONAN DOYLE\nSherlock Holmes trở về...,Sir ARTHUR CONAN DOYLE
4,[Điệu Nam Ai ],Mầu Hoa Khế\nĐiệu Nam Ai\nBắt đầu tới tuổi 13 ...,Mầu Hoa Khế
...,...,...,...
7285,[Con có yêu mẹ không_ ],Peter Carey\nCon có yêu mẹ không?\nLời giới th...,Peter Carey
7286,[Tượng Đài Thương Tiếc ],Mặc Nhiên\nTượng Đài &quot;Thương Tiếc &quot;\...,Mặc Nhiên
7287,[Mất Hút Xuân Thì ],Ấu Tím\nMất Hút Xuân Thì\nTiếng muỗng đĩa lanh...,Ấu Tím
7288,[Mẹ Tôi và bí ẩn tâm linh ],Kim Phương Oanh\nMẹ Tôi và bí ẩn tâm linh\n- M...,Kim Phương Oanh
7289,[Tình viễn xứ ],Rjorie Shoebridge\nTình viễn xứ\nDịch giả: Ngu...,Rjorie Shoebridge

# Preprocessing

In [10]:
import re, unicodedata, random
import pandas as pd
from typing import List, Iterable, Union

class TextPreprocessor:
    QUOTE_MAP = {
        '“':'"', '”':'"', '„':'"', '‟':'"', '〝':'"', '〞':'"',
        '‘':"'", '’':"'", '‚':"'", '‛':"'", '´':"'", '`':"'"
    }

    DEFAULT_DROP_PATTERNS = [
        r"(?im)^\s*mục\s*lục\s*$",
        r"(?im)^\s*lời\s*cuối.*$",
        r"(?im)^\s*nguồn\s*:.*$",
        r"(?im)^\s*phát\s*hành\s*:.*$",
        r"(?im)^\s*chào mừng.*(dự án|đón đọc).*$",
        r"http[s]?://\S+",
    ]

    def __init__(self,
                 para_token="<PARA>",
                 bos_token="<BOS>",
                 eos_token="<EOS>",
                 min_words=200):
        self.PARA, self.BOS, self.EOS = para_token, bos_token, eos_token
        self.min_words = min_words

        # basic cleans
        self.re_ctrl    = re.compile(r"[\u0000-\u0008\u000B-\u000C\u000E-\u001F]")
        self.re_spaces  = re.compile(r"[ \t]+")
        self.re_manynl  = re.compile(r"\n{3,}")
        self.re_ws_nl   = re.compile(r"[ \t]+(\n)|(\n)[ \t]+")
        self.drop_res   = [re.compile(p) for p in self.DEFAULT_DROP_PATTERNS]

        # punctuation normalization
        self.re_space_before_punct = re.compile(r"\s+([.,!?;:])")     
        self.re_need_space_after   = re.compile(r"([.,!?;:])([^\s])")  

    def _normalize_unicode(self, s: str) -> str:
        s = unicodedata.normalize("NFC", s or "")
        for k, v in self.QUOTE_MAP.items():
            s = s.replace(k, v)
        return s

    def _strip_boilerplate(self, s: str) -> str:
        lines = []
        for line in s.splitlines():
            if any(rgx.search(line) for rgx in self.drop_res):
                continue
            lines.append(line)
        return "\n".join(lines)

    def clean_text(self, s: str) -> str:
        s = self._normalize_unicode(s)
        s = self._strip_boilerplate(s)

        s = self.re_ctrl.sub(" ", s)
        s = self.re_spaces.sub(" ", s)
        s = self.re_manynl.sub("\n\n", s)
        s = self.re_ws_nl.sub(lambda m: "\n", s)
        s = s.strip()

        s = s.replace("\n\n", f" {self.PARA} ")
        s = s.replace("\n", " ")

        s = self.re_space_before_punct.sub(r"\1", s)
        s = self.re_need_space_after.sub(r"\1 \2", s)

        s = re.sub(r"\s+", " ", s).strip()

        return s

    def process_series(self, texts: Union[pd.Series, Iterable[str]]) -> List[str]:
        seq = texts.tolist() if isinstance(texts, pd.Series) else list(texts)
        records = []
        for t in seq:
            clean = self.clean_text(str(t))
            if len(clean.split()) >= self.min_words:
                records.append(f"{self.BOS} {clean} {self.EOS}")
        return records

In [11]:
proc = TextPreprocessor(min_words=50)

train_records = proc.process_series(train_df["Texts"])
test_records = proc.process_series(test_df["Texts"])
val_records = proc.process_series(val_df["Texts"])

In [12]:
train_df.iloc[0]['Texts']

'Hòa Đa\nSanh Rớt\nThời gian gặp lại vợ con, sau khi học cải tạo cũng qua mau             Ngày tháng cứ dần trôi mà tôi không biết phải làm gì hơn là cứ quanh quẩn trông chừng hai đứa nhỏ, giúp vợ rảnh tay ngược xuôi, mua đầu chợ bán cuối chợ, kiếm sống qua ngày.  Cũng có lúc tôi thử bán buôn như vợ, nhưng có lẽ do bản tính thày giáo nên không thích ứng được với sinh hoạt chụp giựt, mua đấp bán đổi, lúc nào cũng phải nói láo để kiếm lời.  Hồng cũng cố gắng tạo điều kiện để tôi không phải làm những việc xem chừng không mấy thích hợp với tính khí của tôi... Rồi tôi cũng được một thằng bạn giúp tìm đồ nghề vá xe đạp cạnh lề đường; những lúc đó, Hồng ở nhà trông chừng con hay gửi con  hàng xóm, học trò cũ... để chạy hàng. Cuộc sống mới sao mà thê lương ảm đạm đến thế!             Một buổi chiều, Hồng về nhà trông có vẻ mệt mỏi và lo lắng: - Sáu Thủy mới gặp em nói, nhà mình có tên trong danh sách đi kinh tế mới, danh sách chỉ gồm những hộ ngụy quân ngụy quyền và mấy hộ có vấn đề về xã hội.  Ý này do bà Sáu Xê bên Mặt Trận đưa ra, bà ấy nói là anh là sĩ quan ngụy không có việc làm, em chỉ buôn bán tạp chủ yếu làm trung gian kiếm lời, không trực tiếp sản xuất ra của cải vật chất hay tinh thần gì, nhà lại mướn ngay trước mặt cơ quan của Thị Xã Ùy...  Sáu Thủy với tư cách Phụ Nữ Phường  có biện hộ cho mình: anh mới học cải tạo về, đã góp đơn với Ty Giáo Dục, hiện đang chờ cứu xét... nhưng Sáu Thủy cũng cho biết xem chừng ý kiến cùa chỉ không thuyết phục được ủy ban. Chị ấy nói mình nên tính trước, nếu có thể, tìm cách về nông thôn gần đây, hơn là ngồi chờ bị đưa đi kinh tế mới.  Anh tính sao? - Anh cũng không biết tính sao nữa, có lẽ như thế thì hơn.  Với lý lịch của anh, với hai thằng em sĩ quan ngụy, một nhảy dù, một thảy quân lục chiến, anh chẳng mong gì đơn xin dạy lại được chấp thuận. Nhưng mà đi đâu bây giờ, mình đâu còn vốn liếng  hay tiền bạc gì! - Em vẫn còn giữ mớ nữ trang cưới, hồi đó túng mấy em cũng không dám bán, bây giờ cùng lắm mình bán lấy tiền mua đất.  Chớ nếu đi kinh tế mới, lần hồi rồi cũng tiêu luôn... Hai con còn nhỏ, đi kinh tế mới, rừng sâu nước độc... rồi còn chuyện học hành, không lẽ anh định để tụi nó không đi học? - Anh không biết gì về ruộng nương, cũng không quen biết ai có thể giúp mình, không biết phải làm sao đây...             Vài tuần sau, Hồng báo tin: - Mấy hôm trước, em gặp thím Mười, Má của Hồng Thu, học trò anh, ở ngoài chợ.  Thấy em buồn buồn, thím hỏi thăm, em cũng kể thiệt hoàn cảnh của mình...  Hôm nay thím gặp lại em, nói có kể chuyện mình cho chú Mười nghe.  Chú nói, ruộng của chú hiến cho nhà nước mấy tháng trước rồi, không còn để chia cho mình nữa, nhưng anh của chú thì còn, chú nói anh thu xếp, chú dẫn gặp anh của chú và chỉ cho cách làm giấy tờ nhường cơm xẻ áo, bây giờ ruộng đất do nhà nước quản lý, đâu có ai buôn bán gì được. - Có xa lắm không? - Không, ở trong Phước Trinh, gần đây thôi, chú Mười vẫn sáng đi chiều về để làm ruộng.  thím Mười nói, thà như vậy còn hơn đi kinh tế mới.   * *   *             Và như vậy, với hơn lượng vàng mười tám nữ trang cưới, tôi đổi được bốn công ruộng gò, cỏ năng và lát mọc tốt hơn lúa, gia đình tôi bắt đầu cuộc sống của một nông dân. từ cuối năm một chín bảy bảy.             Ngày ra xã ký giấy tờ chứng nhận nhường cơm xẻ áo và giao nữ trang, Chú Sáu, anh chú Mười nói an ủi tôi:&quot;Thày giáo đừng buồn, cháu tui học thày cũng như con tui học thày, tui nói chỉ một lời, ngày nào thày giáo không làm ruộng nữa, trả đất lại tui, tui quờn tiền lại cho thày, cứ căng theo giá lúa bây giờ và lúc đó mà tính.  Có em tui đây làm chứng, tui nói là chắc mà thôi&quot;.             Chỉ có thế, không giấy tờ sang nhượng, cũng không có một tờ giấy nào làm bằng ngoài tờ  đơn nhường cơm xẻ áo của  chủ đất và lời chứng nhận của xã .  Tôi không có lựa chọn nào khác.             Mấy người bạn, cũng là giáo chức biệt phái, cùng đi học tâp cải tạo, bỏ hai ngày công để phụ đào mương  lấy đất đắp nền nhà.  Ngày khởi công, anh Chất hỏi sao không cúng dộng thổ, anh Bá cười nói: &quot;Biểu thằng Thạnh cúng cũng như không, nó có thể chiều ý mà cúng, nhưng nó không tin đâu!&quot; Anh Đạt bắt ngừng lại, chạy đi một lúc quay lại với vài cái bánh bơ, mấy điếu thuốc và vài cây nhang. Anh nói :&quot;Đất có Thổ Công, sông có Hà Bá, đừng có làm bậy. Không thấy lợi gì thì trước mắt cũng không hại ai. Thạnh, thắp nhang lên rồi khấn đi&quot;...             Ngày lại ngày qua, tôi tập sống, ăn nói và hành xử giống một nông dân.  Nhưng giữa tôi và người địa phương vẫn có ít nhiều khác biệt, mặc dù họ không có ý gì đối xử phân biệt.  Có hay chăng là trong mấy buổi nhậu, tôi vốn không uống đươc rượu; bia uống một chai đã say, nói chi đến rượu đế, thứ rượu không còn được nấu với gạo hay nếp như xưa mà được nấu bằng bọt đường.  Những ngày đầu ra ruộng, tôi còn chưa phân biệt được cỏ chát và lúa, học dần từng chút với người địa phương, bắt đầu từ những điều sơ đẳng nhất, như trẻ con mới lần đầu học vần.  Mà trong công việc đồng áng, tôi nào có khác trẻ mới học vần? Cũng kể từ lúc ấy, tôi có một tên mới &quot;Năm thày giáo&quot;.             Vụ lúa đầu tiên, hè thu bảy mươi tám, tôi thu hoạch được hơn một giạ lúa trên một công ruộng làm thử, sau khi bỏ ra hai giạ giống, một giạ ngâm không lên, và một giạ bị nước chụp sau khi sạ chừng bốn năm ngày, không kể tiền công trâu.   Bà con qua lại, nhìn tôi lắc đầu ái ngại...Thời gian này, Hồng đang có thai.              Đất xấu, không chỗ làm mạ, tôi quyết định sạ lúa mùa. Ba công đất, sạ một giạ  lúa &quot;rẩy xe&quot;, một loại lúa hạt tròn, khô cơm, nhưng chịu hạn, chịu úng giỏi. Tháng bảy tháng tám trời hạn, khí tượng nhà nước tiên đoán &quot;năm nay hạn kéo dài, do mực nước sông Tiền đo được ở Tân Châu, và mực nước sông Hậu đo được ở Châu Đốc xuống thấp hơn mức bính thường...&quot; Bước qua tháng chín âm lịch, trời đổ mưa, mưa bù cho mấy tháng trước bị hạn. Nước không rút được ra sông cái vì nước sông Cửu Long đang đổ về, dồn ứ trong ruộng. Tôi nhớ lại lời của bác Sáu Liễn nói tháng trước :&quot;Năm nay không khéo bị lụt a, thày giáo - Sao bác biết? - Hôm trước phát cỏ bờ, qua thấy ổ ong đất đóng lưng chừng nhánh cỏ tranh, thứ ong này bao giờ cũng đóng ổ sát mặt đất, chỗ gốc tranh, nó đóng trên cao là có chuyện...trời phú cho con vật có tánh linh hay lắm thày giáo à...&quot; Lúa mới cấy chưa bén được đất, bị nước chụp đầu.  Nước, nước nhiều quá, nước cũ chưa rút, mưa lại trút thêm nước, đứng dưới ruộng, nước ngang vai, có chỗ, ngập lút đầu, ruộng lúa biến thành biển nước mênh mông, lúa cấy chưa kịp bén rễ, nổi lên, gió thổi tấp vào bờ đai từng về... tôi nhìn ruộng nước mênh mông mà lắc đầu chán ngán, chuyến này chắc lại trắng tay. Mưa gió thế này, chỉ có nước ngồi khoanh tay ngó trời ngó nước . Hôm nào không mưa dầm. liều mạng vượt hơn hai cây số đường ruộng ngập nước ra thị xã chạy xe đạp ôm kiếm cơm... còn biết làm gì hơn ?             Tháng mười âm lịch, trời vẫn còn mưa. Thường năm, tháng này là tháng nước nổi ở Vĩnh Long, Mỹ tho. Nước sông Cửu Long đang kéo về, đổ ra biển không kịp, khựng lại, cộng thêm nước ứ trong đồng mấy tháng trước dồn ra, nước bắt đầu tràn lên bờ. Miệt Cái Bè, Cai Lậy, nhà cửa, vườn tược nhô lên trên biển nước như những ốc đảo; quốc lộ 4 có đoạn chìm dưới mực nước, giao thông bị gián đoạn, dân chúng tìm chỗ cao, kể cả dốc cầu, cất chòi tạm trú.  Cả vựa lúa của đồng bằng Cửu Long bị ngập úng, mất mùa, chỉ còn vùng Sóc Trăng, Bạc Liêu, Cà Mau, Minh Hải là nằm ngoài vùng thiên tai. Người ta rủ nhau xuống đó làm thuê kiếm sống, người ta mang lư hương, chân đèn, tủ thờ, đi văng, giường hộp... những thứ có giá do bao đời chắt chiu dành dụm được mang xuống đó, đổi lúa gạo mang về. Mà có đi được dễ dàng, xuôi lọt đâu!  Chính sách ngăn sông cấm chợ của nhà nước gây ra không biết bao nhiêu là thảm cảnh.  Bảy Nhiêu mang bộ lư và chân đèn xuống Minh Hải đổi được mười giạ lúa và hơn nửa giạ gạo ăn đường; đêm đi, ngày kiếm lùm liếm bụi lủi vô trốn, vậy mà về tới Giáp Nước, chỉ còn cách nhà nửa ngày đường, anh bị đám công an kinh tế chạy ghe gắn máy đuôi tôm bắt được, tịch thu hết. Anh năn nỉ gảy lưỡi không ăn thua gì, giận mất khôn, chưởi thề vài tiếng, bị bắt nhốt luôn thêm ba bửa nữa, bỏ thằng con sống lêu bêu trên ghe không tiền không gạo...Chuyện của Bảy Nhiêu chỉ là một trong nhiều chuyện bi thảm đó.               Hai ngày rồi, trời cứ mưa, mưa hoài. Nhà hết gạo mà tôi cũng không có cách nào đi ra ngoài để chạy xe kiếm tiền được. Buổi chiều, hai vợ chồng lại gấu ó với nhau. Hồng với bụng chữa vượt mặt, nằm trong giường khóc tấm tức.  Hai đứa nhỏ, thấy cha mẹ cãi cọ, sợ hãi ôm nhau ngủ trong góc; hồi chiều, cả nhà ăn bo bo thay cơm vì không còn gạo. Tôi nằm trên võng, tấm chăn rách đắp hờ ngang bụng, nghĩ lan man hết chuyện này đến chuyện khác, thấy mình quá vô dụng: chèo chống không giỏi, cày bừa không thông, sức lực có hạn... có chăng là một tên gọi đầy mĩa mai: thày giáo và một văn bằng đại học không có khả năng kiếm ra được nắm gạo cho gia đình. Bao năm học hành bây giờ lại sống nhờ vào sức đạp xe đưa khách kiếm tiền mua gạo. Tôi giận mình bất lực, tôi giận xã hội đổi thay, tôi giận luôn tính lương thiện và sĩ khí  không hợp thời của mình... phải chi mình ngu dốt một chút, phải chi mình láu cá một chút, gian manh một chút, liều lĩnh một chút, ti tiện một chút... cứ lan man, lan man nuy nghĩ, tôi chìm vào giấc ngủ lúc nào không hay.             Chợt chiếc võng lắc nhẹ, tiếng Hồng  qua tiếng thở gấp: - Dậy đi anh, em đau bụng quá, chắc sắp sanh, anh dậy đưa em đi nhà thương. Đồ đạc em gói sẵn hết trong túi này rồi.             Mưa vẫn còn rớt hột, tôi vói tay khêu lớn ngọn đèn dầu, nhìn đồng hồ trên bàn, nói một câu vô duyên: - Trời đất, mới hơn mười giờ hè, giờ này ra đường chắc gì đón được xe, em ráng tới mai đượcc không? - Không được đâu anh, đau đẻ chớ phải đau gì đâu mà anh kêu nhịn. Nếu nó giống hai thằng anh nó thì chắc phải vài giờ nữa mới sanh. Ra tới đường, chắc xe lôi cũng bắt đầu chạy rồi. - Đường trơn lắm, em đi có được không?             Tuy nói vậy, tôi vẫn ngồi ngay dậy, lấy áo mưa  cho Hồng và choàng vội tấm ny lông. Lay hai dứa nhỏ dậy, tôi bảo thằng lớn, lúc đó mới lên năm: - Ba đưa mẹ đi nhà thương sanh em bé, con đóng cửa lại ngủ, coi chừng em, sáng sớm mai ba về, đừng có sợ!             Tay trái xách gói đồ đi sanh mà Hồng đã sửa soạn từ trước (gồm mấy bộ quần áo và tả lót còn sót lại của mấy đứa trước và vài bộ đồ của Hồng), tay phải cầm đèn đưa ra phía sau cho Hồng vịn, hai vợ chồng dò từng bước chân vì đường đầy bùn trơn trong tiếng thở mệt nhọc của sản phụ.  Cứ đi chừng hơn mười thước phải ngừng lại cho Hồng thở... Tôi lo ngại nói: - Kiểu này, anh không chắc em ra được đến ngoài đường lộ, hay là mình quay về, anh chạy vào xóm kêu cô Hà ra giúp. - Không sao, em ráng được mà, đi tiếp đi anh, chưa chắc cô Hà có ở nhà đâu.             Cô Hà là một cô mụ  ngoài thị xã. Giải phóng vô, bảo sinh viện tư chỗ cô làm bị đóng cửa, chồng cô Hà là Hải quân trung úy, đang học tập cải tạo, cô không đươc bố trí công tác lại ở nhà thương lớn, nên cũng đành đi đi về về, bán trốn mua chui mà sống...             Ấy vậy mà hai vơ chồng cũng dìu nhau được ra tới nền bót, chỉ còn vượt qua chiếc cầu khỉ  này và chừng vài trăm thước đường ruộng nữa là tới đường lộ. Mưa cũng đã tạnh, tôi nói với Hồng: - Em đứng nghỉ, đợi anh mang túi quần áo qua bên kia  rồi trờ lại đón em qua.             Mây thấp, trời tối đen, chỉ có ánh đèn dầu tôi đang cầm lắc lư, le lói, vài tiếng chó sủa vọng lại từ xóm... mọi người đang say giấc ngủ trong cái thời tiết ẩm ướt quỉ quái này. Tôi để gói đồ và đèn lồng trên một mô đất rồi mò mẫn trong bóng tối quay trở lai đón Hồng, được phần ba cầu thì nghe tiếng thở phì phò của Hồng lần mò qua cầu. Chiếc cầu khỉ này, ban ngày đi còn run chân, vậy mà người đàn bà khốn khổ gần kiệt sức đó vượt qua được.             Hai vợ chồng lại lần mò dìu nhau đi trong bóng tối...               Chợt Hồng rên rĩ, ngồi sụp xuống vệ cỏ, dựa lưng vào gốc xoài bên đường, nức nở: - Em chết mất anh ơi, bọc nước bể rồi, em không còn đi được nữa, chắc em phải sanh rớt ở đây quá.             Tôi thật sự kinh hoàng khi nghe Hồng nói câu đó. Phản xạ tự nhiên, tôi bật dậy, chạy ngược lại xóm cạnh bờ sông, kêu cứu: - Thím chín ơi, thím tám ơi, có ai ở đây không, cứu giùm vợ tôi với. Bớ bà con cô bác ơi, có ai ở nhà không, cứu giùm vợ tôi với.             Cừa ngõ nhà Chín Thắng đóng chặt, nhà xa cửa ngõ quá, tôi không chắc trong nhà nghe tiếng tôi kêu cứu... Giọng tôi lạc đi, tôi chạy cuống quýt, bất chấp bờ bụi, tăm tối... Tôi càn đại xuống sông, bơi sang bờ bên kia, như vậy còn nhanh hơn phải qua cái cầu khỉ lung lay kia...Tôi trườn mình trên bãi bùn, ào lên bờ, đâp cửa nhà chú tám Liễu: - Chú Tám, thím tám ơi, có nhà không, làm ơn cứu giùm vợ cháu với! - Thày giáo hả? chuyện gì vậy? - Vợ cháu đau bụng đẻ, tính đi nhà thương - giọng tôi run rẩy vì lạnh và sợ - không dè đến đây nước ối bị bể rồi, đi không kịp, chú thím giúp giùm nhờ thằng Hai con chú chèo ghe chở giùm vợ cháu ra y tế xã...             Tiếng mở cửa lịch kịch, thím tám bước ra: - Khổ gì mà khổ dữ vậy, cô giáo đang ở đâu? Thằng Hai lấy ghe đi Minh Hải hai ngày nay rồi - Dạ, qua bên kia sông rồi.             Bác Tư Thuận, anh chú Tám Liễu cũng bước ra: - Năm thày giáo lấy xuồng của tao chở nó ra xã mau, mưa gió thế này, đẻ ngoài đường, chết mất.             Tiếng Hai Câu, con trai chú nói vọng từ trong nhà ra cản: - Không được đâu, tía! cổ mà đẻ rớt trên xuồng, tui quăng xuồng luôn, làm ăn gì được nữa? - Thày giáo thông cảm, xuồng tui đi giăng câu kiếm sống đó. hay là thày chạy xuống chú Tám Lính mượn xuồng nhỏ của chú, xuồng ổng dể làm chưn đi trong mùa nước nổi, không có làm ăn gì đâu! - Bây giờ đi ra xã cũng không kịp, thím tám nói chen vào, mà chắc gì y tá có ở đó, mưa gió đêm hôm thế này, đâu có ai ở đó!  bọc nước bể rồi, nó sanh bây giờ, thày giáo chạy xuống kêu bà Ba Thợ mộc, ngày trước bả là mụ vườn đó, mau đi chớ không kịp, tui với chị tư qua đó trước, cổ nằm chỗ nào? - Dạ, cạnh gốc xoài ở cuối vườn bà Tư Thỏ Nói xong, tôi lập cập chạy xuống nhà bà Ba Thợ mộc...               Lúc tôi đâm được xuồng vào bờ, tóm vội dây xuồng vào cọc chiếc cầu khỉ nền bót, nhảy lên bờ thì đã thấy ánh của năm ba chiêc đèn lồng chỗ Hồng ngồi và tiếng cười nói lao xao của mấy bà. Tôi hỏi lớn: - Sao rồi thím Tám? - Cổ sanh rồi, thày giáo ơi, con gái...             Nỗi mệt nhọc tan biến gần như tức khắc, tôi hỏi tiếp: - Nhau ra chưa? - Chưa, tiếng bà Ba Thợ mộc, để đó tao lo, chút xíu nữa là xong...             Tôi đi lần tới, không còn cảm thấy lo sợ, mệt nhọc, lạnh lẽo. Tiếng Hai Đông: - Thày giáo, nghe mấy bả lao xao, tui ra coi thử... vợ tui phụ với mấy bả ở đẳng, lúc nghe thím tám la &quot;con nhỏ xổ rồi&quot;, tui coi đồng hồ, nó lọt lòng lúc 1 giờ 57 sáng, tui chờ để nói cho thày hay! - Ô, cám ơn anh hai nhiều lắm. - Tụi mình mà, tui cũng như thày giáo thôi, ơn nghĩa gì mà thày nói.  Mình đàn ông, lại đó không tiện, ngồi đây chờ coi có gì tiếp cứu.             Nhau ra rồi! Cầm lá nhau trơn tuột, tôi quan sát kỹ dưới ánh đèn dầu, nhau tróc đều...tôi yên tâm. Những năm tháng biến động của Mậu Thân ngày trước, một lần trực phòng y tế của trạm  tiếp cư nạn nhân chiến tranh với một sinh viên y khoa, tôi đã phảu làm phụ tá bất đắc dĩ trong một ca đẻ tại trại vì giới nghiêm toàn thành phố, không có cách gì chở sản phụ đi nhà thương được; anh bạn y khoa đã chỉ cho tôi coi hình dạng và tình trạng lá nhau của sản phụ để có thể đoán coi nhau còn sót hay không. - Bây giờ êm rồi, tiếng thím Chín Thắng, thày giáo phụ đưa cổ xuống xuồng. - Nếu không còn gì nguy hiểm cháu muốn đưa vợ cháu về nhà, còn hai đứa nhỏ ở nhà một mình... - Vậy thì mau lên, bà Ba Thợ mộc nói, để lâu quá không nên, về lẹ kiếm củi đốt xông cho ấm, để lâu, hàn nhập lý, cổ không chết sau này cũng bịnh rề rề, còn khổ nữa... sẵn tụi tui cũng phải qua sông, phụ kéo xuồng qua mặt đập, rồi thày giáo chống riết trên ruộng về nhà.             Mây lại kéo tới úp chụp trên đầu, trời tối như bưng mắt, nhìn không quá hai thước qua ánh đèn lồng trước để trên mũi xuồng. Hồng nằm dài trên tấm ván xuồng gồ ghề nứt nẻ, dưới tấm ny lông và mớ quần áo ướt át, con nhỏ được quấn trong chiêc khăn lông nằm trong tay mẹ nó. Tôi quặc tay giầm, móc cho mũi xuồng hướng vào mặt đập. Xạc! mũi xuồng gối lên đám lục bình dày đặc trước đập, xuồng chòng chành, chiếc đèn lồng rơi xuống sông, tôi cảm thấy ướt chỗ ván ngồi:&quot; chết cha! - tôi nghĩ nhanh - nước vô xuồng...&quot; tôi tụt nhanh xuống sông, hai tay nâng, đẩy nhanh xuồng vào mặt đập. Tiếng Hồng kêu lên: - Anh! anh!, nước vô xuồng! - Anh biết rồi, em bình tỉnh, không sao đâu, tôi trấn an             Hồng đã ngồi dậy trong xuồng, lưng ướt đẫm, tay đỡ con nhỏ nâng lên cao. Tôi đứng  nước mấp mé vai, gồng sức nâng xuồng lên cao... - Chèng ơi! - thím Tám Liễu kêu lên - gì nữa đây? - Dạ, nước vô xuồng, thím tám ơi, Hồng nói. - Chết chớ phải chơi sao, bà Ba Thợ mộc la lên, mau phụ kéo nó lên bờ mau. Có sao không cô giáo? - Cháu không sao, chỉ bị ướt hết lưng, tiếng Hồng run run. - Chèng đét, mới sanh xong đã bị ướt mà còn nói không sao. Thôi bây giờ tím Tám cầm đèn đi trước, thày giáo cõng cô giáo theo sau, tụi tui ôm đồ theo sau hết.  Thày giáo nhớ, mệt thì nghỉ, để trợt té là cổ chết luôn.             &quot;Té là chết luôn, té là chết luôn...&quot; cõng Hồng trên lưng mà câu nói của bá Ba thợ mộc cứ vang vang trong tai, &quot;Té là chết luôn, té là chết luôn...&quot;  Đường trơn như mỡ, sức nặng trên lưng, tôi lặt lè bấm chân bước từng bước một &quot;Té là chết luôn, té là chết luôn...&quot; Tôi cảm thấy như có giòng nước ấm chảy dài trên lưng &quot;Té là chết luôn, té là chết luôn...&quot;             Chỉ còn chừng hơn trăm thước nữa là đến nhà, trời lại bắt đầu lắc rắc, tiếng sấm gầm gừ từ xa, ánh chớp loang loáng... có tiếng thím tám phía trước: - Mau lên thày giáo, cô giáo trúng cơn mưa này là không xong đâu... ông Trời à! làm ơn chờ vợ chồng nó về tới nhà rồi hẵng mưa... Ráng chút lên thày giáo!             Tôi bậm miệng bước tới, bước tới... không còn cảm giác nào khác, cứ bước tới... bước tới... bước tới... Sấm nổ ầm ầm, chớp lóe loang loáng, hàng trâm bầu vật vã vì gió...               Vừa lúc đặt được Hồng xuống giường thì mưa gió ập tới; mấy bà, người phụ thay quần áo khô cho Hồng, người lo nhúm lửa hơ... - Coi chừng có củi giá không, khói củi giá độc lắm, sưng mình mẩy chết, bà Ba Thợ mộc nói. - Con nhỏ chết lạnh bây giờ không sợ, lại sợ khói, thím Tám Liễu đáp, chèng ơi củi gì mà ướt mem, chừng nào mới cháy đây.             Tôi rút vội mấy cuốn sách trên kệ gỗ tạp đóng sơ sài, không kịp nhìn đó là sách gì: - Thím cứ lấy đốt, không có củi giá đâu, trâm bầu đó, nóng một chút chảy nhựa là cháy ngay.             Mùi dầu gió xông nồng nặc, tiếng bà Ba Thợ mộc nói &quot;thím chín chà mạnh tay lên chỗ ngực và bụng của nó cho ấm&quot;             Mưa gió dập đùng đùng vào vách lá, tôi phải chạy vội ra ngoài, cột lại tấm ny lông và che thêm nửa tấm lều vải cá nhân còn sót lại từ hồi đi Thủ Đức chổ giường nằm cho khỏi bị tạt mưa và kín gió.  Hai đứa nhỏ cũng thức dậy, ngồi thu lu trong góc giường của chúng nhìn người lớn lăng xăng quanh mẹ nó             * *   *             Mưa dịu lần, lửa cũng đã bén cháy, mùi khói tỏa ấm trong nhà, mẹ con sản phụ cũng nằm yên, hai thằng con đang tò mò ngắm nhìn em bé còn đỏ hõn quấn gọn trong chiếc khăn lông.             Tôi nấu ấm nước, pha bình nước nóng, mời mấy bà.  Thím Chín Thắng kể lại :&quot;Lúc nghe tiếng kêu, má tôi nói, tiếng ai tuồng như tiếng Năm Thày Giáo, bây ra thử coi. Tui ra không thấy ai, bên kia, vơ Hai Đông cũng cầm đèn bước ra hỏi, gì vậy thím chín? - hổng biết, tuồng như có ai kêu cứu - cháu cũng nghe như vậy.  Hai đứa tôi bước hẳn ra bờ ngó lên ngó xuống thì thấy ánh đèn lồng chỗ cô giáo. Tụi tôi bước tới thì chèng ơi, con nhỏ xổ rồi, cô giáo đang hai tay bụm đứa nhỏ. Tôi la làng, má tôi chạy vô nhà lôi chiếc chiếu... Thím Tám Liễu chen vô: lúc đó tui với chị tư đang ở bên kia cầu chờ bà Ba, trời mưa đường trơn đêm hôm qua cái cầu khỉ đó, nói thiệt, cũng ớn, nghe chị kêu, hai chị em phang qua... kế bà ba tới cắt rún cho con nhỏ

In [13]:
train_records[0]

'<BOS> Hòa Đa Sanh Rớt Thời gian gặp lại vợ con, sau khi học cải tạo cũng qua mau Ngày tháng cứ dần trôi mà tôi không biết phải làm gì hơn là cứ quanh quẩn trông chừng hai đứa nhỏ, giúp vợ rảnh tay ngược xuôi, mua đầu chợ bán cuối chợ, kiếm sống qua ngày. Cũng có lúc tôi thử bán buôn như vợ, nhưng có lẽ do bản tính thày giáo nên không thích ứng được với sinh hoạt chụp giựt, mua đấp bán đổi, lúc nào cũng phải nói láo để kiếm lời. Hồng cũng cố gắng tạo điều kiện để tôi không phải làm những việc xem chừng không mấy thích hợp với tính khí của tôi. .. Rồi tôi cũng được một thằng bạn giúp tìm đồ nghề vá xe đạp cạnh lề đường; những lúc đó, Hồng ở nhà trông chừng con hay gửi con hàng xóm, học trò cũ. .. để chạy hàng. Cuộc sống mới sao mà thê lương ảm đạm đến thế! Một buổi chiều, Hồng về nhà trông có vẻ mệt mỏi và lo lắng: - Sáu Thủy mới gặp em nói, nhà mình có tên trong danh sách đi kinh tế mới, danh sách chỉ gồm những hộ ngụy quân ngụy quyền và mấy hộ có vấn đề về xã hội. Ý này do bà Sáu Xê bên Mặt Trận đưa ra, bà ấy nói là anh là sĩ quan ngụy không có việc làm, em chỉ buôn bán tạp chủ yếu làm trung gian kiếm lời, không trực tiếp sản xuất ra của cải vật chất hay tinh thần gì, nhà lại mướn ngay trước mặt cơ quan của Thị Xã Ùy. .. Sáu Thủy với tư cách Phụ Nữ Phường có biện hộ cho mình: anh mới học cải tạo về, đã góp đơn với Ty Giáo Dục, hiện đang chờ cứu xét. .. nhưng Sáu Thủy cũng cho biết xem chừng ý kiến cùa chỉ không thuyết phục được ủy ban. Chị ấy nói mình nên tính trước, nếu có thể, tìm cách về nông thôn gần đây, hơn là ngồi chờ bị đưa đi kinh tế mới. Anh tính sao? - Anh cũng không biết tính sao nữa, có lẽ như thế thì hơn. Với lý lịch của anh, với hai thằng em sĩ quan ngụy, một nhảy dù, một thảy quân lục chiến, anh chẳng mong gì đơn xin dạy lại được chấp thuận. Nhưng mà đi đâu bây giờ, mình đâu còn vốn liếng hay tiền bạc gì! - Em vẫn còn giữ mớ nữ trang cưới, hồi đó túng mấy em cũng không dám bán, bây giờ cùng lắm mình bán lấy tiền mua đất. Chớ nếu đi kinh tế mới, lần hồi rồi cũng tiêu luôn. .. Hai con còn nhỏ, đi kinh tế mới, rừng sâu nước độc. .. rồi còn chuyện học hành, không lẽ anh định để tụi nó không đi học? - Anh không biết gì về ruộng nương, cũng không quen biết ai có thể giúp mình, không biết phải làm sao đây. .. Vài tuần sau, Hồng báo tin: - Mấy hôm trước, em gặp thím Mười, Má của Hồng Thu, học trò anh, ở ngoài chợ. Thấy em buồn buồn, thím hỏi thăm, em cũng kể thiệt hoàn cảnh của mình. .. Hôm nay thím gặp lại em, nói có kể chuyện mình cho chú Mười nghe. Chú nói, ruộng của chú hiến cho nhà nước mấy tháng trước rồi, không còn để chia cho mình nữa, nhưng anh của chú thì còn, chú nói anh thu xếp, chú dẫn gặp anh của chú và chỉ cho cách làm giấy tờ nhường cơm xẻ áo, bây giờ ruộng đất do nhà nước quản lý, đâu có ai buôn bán gì được. - Có xa lắm không? - Không, ở trong Phước Trinh, gần đây thôi, chú Mười vẫn sáng đi chiều về để làm ruộng. thím Mười nói, thà như vậy còn hơn đi kinh tế mới. * * * Và như vậy, với hơn lượng vàng mười tám nữ trang cưới, tôi đổi được bốn công ruộng gò, cỏ năng và lát mọc tốt hơn lúa, gia đình tôi bắt đầu cuộc sống của một nông dân. từ cuối năm một chín bảy bảy. Ngày ra xã ký giấy tờ chứng nhận nhường cơm xẻ áo và giao nữ trang, Chú Sáu, anh chú Mười nói an ủi tôi: &quot; Thày giáo đừng buồn, cháu tui học thày cũng như con tui học thày, tui nói chỉ một lời, ngày nào thày giáo không làm ruộng nữa, trả đất lại tui, tui quờn tiền lại cho thày, cứ căng theo giá lúa bây giờ và lúc đó mà tính. Có em tui đây làm chứng, tui nói là chắc mà thôi&quot; . Chỉ có thế, không giấy tờ sang nhượng, cũng không có một tờ giấy nào làm bằng ngoài tờ đơn nhường cơm xẻ áo của chủ đất và lời chứng nhận của xã. Tôi không có lựa chọn nào khác. Mấy người bạn, cũng là giáo chức biệt phái, cùng đi học tâp cải tạo, bỏ hai ngày công để phụ đào mương lấy đất đắp nền nhà. Ngày khởi công, anh Chất hỏi sao không cúng dộng thổ, anh Bá cười nói: &quot; Biểu thằng Thạnh cúng cũng như không, nó có thể chiều ý mà cúng, nhưng nó không tin đâu! &quot; Anh Đạt bắt ngừng lại, chạy đi một lúc quay lại với vài cái bánh bơ, mấy điếu thuốc và vài cây nhang. Anh nói: &quot; Đất có Thổ Công, sông có Hà Bá, đừng có làm bậy. Không thấy lợi gì thì trước mắt cũng không hại ai. Thạnh, thắp nhang lên rồi khấn đi&quot; .. . Ngày lại ngày qua, tôi tập sống, ăn nói và hành xử giống một nông dân. Nhưng giữa tôi và người địa phương vẫn có ít nhiều khác biệt, mặc dù họ không có ý gì đối xử phân biệt. Có hay chăng là trong mấy buổi nhậu, tôi vốn không uống đươc rượu; bia uống một chai đã say, nói chi đến rượu đế, thứ rượu không còn được nấu với gạo hay nếp như xưa mà được nấu bằng bọt đường. Những ngày đầu ra ruộng, tôi còn chưa phân biệt được cỏ chát và lúa, học dần từng chút với người địa phương, bắt đầu từ những điều sơ đẳng nhất, như trẻ con mới lần đầu học vần. Mà trong công việc đồng áng, tôi nào có khác trẻ mới học vần? Cũng kể từ lúc ấy, tôi có một tên mới &quot; Năm thày giáo&quot; . Vụ lúa đầu tiên, hè thu bảy mươi tám, tôi thu hoạch được hơn một giạ lúa trên một công ruộng làm thử, sau khi bỏ ra hai giạ giống, một giạ ngâm không lên, và một giạ bị nước chụp sau khi sạ chừng bốn năm ngày, không kể tiền công trâu. Bà con qua lại, nhìn tôi lắc đầu ái ngại. .. Thời gian này, Hồng đang có thai. Đất xấu, không chỗ làm mạ, tôi quyết định sạ lúa mùa. Ba công đất, sạ một giạ lúa &quot; rẩy xe&quot; , một loại lúa hạt tròn, khô cơm, nhưng chịu hạn, chịu úng giỏi. Tháng bảy tháng tám trời hạn, khí tượng nhà nước tiên đoán &quot; năm nay hạn kéo dài, do mực nước sông Tiền đo được ở Tân Châu, và mực nước sông Hậu đo được ở Châu Đốc xuống thấp hơn mức bính thường. .. &quot; Bước qua tháng chín âm lịch, trời đổ mưa, mưa bù cho mấy tháng trước bị hạn. Nước không rút được ra sông cái vì nước sông Cửu Long đang đổ về, dồn ứ trong ruộng. Tôi nhớ lại lời của bác Sáu Liễn nói tháng trước: &quot; Năm nay không khéo bị lụt a, thày giáo - Sao bác biết? - Hôm trước phát cỏ bờ, qua thấy ổ ong đất đóng lưng chừng nhánh cỏ tranh, thứ ong này bao giờ cũng đóng ổ sát mặt đất, chỗ gốc tranh, nó đóng trên cao là có chuyện. .. trời phú cho con vật có tánh linh hay lắm thày giáo à. .. &quot; Lúa mới cấy chưa bén được đất, bị nước chụp đầu. Nước, nước nhiều quá, nước cũ chưa rút, mưa lại trút thêm nước, đứng dưới ruộng, nước ngang vai, có chỗ, ngập lút đầu, ruộng lúa biến thành biển nước mênh mông, lúa cấy chưa kịp bén rễ, nổi lên, gió thổi tấp vào bờ đai từng về. .. tôi nhìn ruộng nước mênh mông mà lắc đầu chán ngán, chuyến này chắc lại trắng tay. Mưa gió thế này, chỉ có nước ngồi khoanh tay ngó trời ngó nước. Hôm nào không mưa dầm. liều mạng vượt hơn hai cây số đường ruộng ngập nước ra thị xã chạy xe đạp ôm kiếm cơm. .. còn biết làm gì hơn? Tháng mười âm lịch, trời vẫn còn mưa. Thường năm, tháng này là tháng nước nổi ở Vĩnh Long, Mỹ tho. Nước sông Cửu Long đang kéo về, đổ ra biển không kịp, khựng lại, cộng thêm nước ứ trong đồng mấy tháng trước dồn ra, nước bắt đầu tràn lên bờ. Miệt Cái Bè, Cai Lậy, nhà cửa, vườn tược nhô lên trên biển nước như những ốc đảo; quốc lộ 4 có đoạn chìm dưới mực nước, giao thông bị gián đoạn, dân chúng tìm chỗ cao, kể cả dốc cầu, cất chòi tạm trú. Cả vựa lúa của đồng bằng Cửu Long bị ngập úng, mất mùa, chỉ còn vùng Sóc Trăng, Bạc Liêu, Cà Mau, Minh Hải là nằm ngoài vùng thiên tai. Người ta rủ nhau xuống đó làm thuê kiếm sống, người ta mang lư hương, chân đèn, tủ thờ, đi văng, giường hộp. .. những thứ có giá do bao đời chắt chiu dành dụm được mang xuống đó, đổi lúa gạo mang về. Mà có đi được dễ dàng, xuôi lọt đâu! Chính sách ngăn sông cấm chợ của nhà nước gây ra không biết bao nhiêu là thảm cảnh. Bảy Nhiêu mang bộ lư và chân đèn xuống Minh Hải đổi được mười giạ lúa và hơn nửa giạ gạo ăn đường; đêm đi, ngày kiếm lùm liếm bụi lủi vô trốn, vậy mà về tới Giáp Nước, chỉ còn cách nhà nửa ngày đường, anh bị đám công an kinh tế chạy ghe gắn máy đuôi tôm bắt được, tịch thu hết. Anh năn nỉ gảy lưỡi không ăn thua gì, giận mất khôn, chưởi thề vài tiếng, bị bắt nhốt luôn thêm ba bửa nữa, bỏ thằng con sống lêu bêu trên ghe không tiền không gạo. .. Chuyện của Bảy Nhiêu chỉ là một trong nhiều chuyện bi thảm đó. Hai ngày rồi, trời cứ mưa, mưa hoài. Nhà hết gạo mà tôi cũng không có cách nào đi ra ngoài để chạy xe kiếm tiền được. Buổi chiều, hai vợ chồng lại gấu ó với nhau. Hồng với bụng chữa vượt mặt, nằm trong giường khóc tấm tức. Hai đứa nhỏ, thấy cha mẹ cãi cọ, sợ hãi ôm nhau ngủ trong góc; hồi chiều, cả nhà ăn bo bo thay cơm vì không còn gạo. Tôi nằm trên võng, tấm chăn rách đắp hờ ngang bụng, nghĩ lan man hết chuyện này đến chuyện khác, thấy mình quá vô dụng: chèo chống không giỏi, cày bừa không thông, sức lực có hạn. .. có chăng là một tên gọi đầy mĩa mai: thày giáo và một văn bằng đại học không có khả năng kiếm ra được nắm gạo cho gia đình. Bao năm học hành bây giờ lại sống nhờ vào sức đạp xe đưa khách kiếm tiền mua gạo. Tôi giận mình bất lực, tôi giận xã hội đổi thay, tôi giận luôn tính lương thiện và sĩ khí không hợp thời của mình. .. phải chi mình ngu dốt một chút, phải chi mình láu cá một chút, gian manh một chút, liều lĩnh một chút, ti tiện một chút. .. cứ lan man, lan man nuy nghĩ, tôi chìm vào giấc ngủ lúc nào không hay. Chợt chiếc võng lắc nhẹ, tiếng Hồng qua tiếng thở gấp: - Dậy đi anh, em đau bụng quá, chắc sắp sanh, anh dậy đưa em đi nhà thương. Đồ đạc em gói sẵn hết trong túi này rồi. Mưa vẫn còn rớt hột, tôi vói tay khêu lớn ngọn đèn dầu, nhìn đồng hồ trên bàn, nói một câu vô duyên: - Trời đất, mới hơn mười giờ hè, giờ này ra đường chắc gì đón được xe, em ráng tới mai đượcc không? - Không được đâu anh, đau đẻ chớ phải đau gì đâu mà anh kêu nhịn. Nếu nó giống hai thằng anh nó thì chắc phải vài giờ nữa mới sanh. Ra tới đường, chắc xe lôi cũng bắt đầu chạy rồi. - Đường trơn lắm, em đi có được không? Tuy nói vậy, tôi vẫn ngồi ngay dậy, lấy áo mưa cho Hồng và choàng vội tấm ny lông. Lay hai dứa nhỏ dậy, tôi bảo thằng lớn, lúc đó mới lên năm: - Ba đưa mẹ đi nhà thương sanh em bé, con đóng cửa lại ngủ, coi chừng em, sáng sớm mai ba về, đừng có sợ! Tay trái xách gói đồ đi sanh mà Hồng đã sửa soạn từ trước (gồm mấy bộ quần áo và tả lót còn sót lại của mấy đứa trước và vài bộ đồ của Hồng), tay phải cầm đèn đưa ra phía sau cho Hồng vịn, hai vợ chồng dò từng bước chân vì đường đầy bùn trơn trong tiếng thở mệt nhọc của sản phụ. Cứ đi chừng hơn mười thước phải ngừng lại cho Hồng thở. .. Tôi lo ngại nói: - Kiểu này, anh không chắc em ra được đến ngoài đường lộ, hay là mình quay về, anh chạy vào xóm kêu cô Hà ra giúp. - Không sao, em ráng được mà, đi tiếp đi anh, chưa chắc cô Hà có ở nhà đâu. Cô Hà là một cô mụ ngoài thị xã. Giải phóng vô, bảo sinh viện tư chỗ cô làm bị đóng cửa, chồng cô Hà là Hải quân trung úy, đang học tập cải tạo, cô không đươc bố trí công tác lại ở nhà thương lớn, nên cũng đành đi đi về về, bán trốn mua chui mà sống. .. Ấy vậy mà hai vơ chồng cũng dìu nhau được ra tới nền bót, chỉ còn vượt qua chiếc cầu khỉ này và chừng vài trăm thước đường ruộng nữa là tới đường lộ. Mưa cũng đã tạnh, tôi nói với Hồng: - Em đứng nghỉ, đợi anh mang túi quần áo qua bên kia rồi trờ lại đón em qua. Mây thấp, trời tối đen, chỉ có ánh đèn dầu tôi đang cầm lắc lư, le lói, vài tiếng chó sủa vọng lại từ xóm. .. mọi người đang say giấc ngủ trong cái thời tiết ẩm ướt quỉ quái này. Tôi để gói đồ và đèn lồng trên một mô đất rồi mò mẫn trong bóng tối quay trở lai đón Hồng, được phần ba cầu thì nghe tiếng thở phì phò của Hồng lần mò qua cầu. Chiếc cầu khỉ này, ban ngày đi còn run chân, vậy mà người đàn bà khốn khổ gần kiệt sức đó vượt qua được. Hai vợ chồng lại lần mò dìu nhau đi trong bóng tối. .. Chợt Hồng rên rĩ, ngồi sụp xuống vệ cỏ, dựa lưng vào gốc xoài bên đường, nức nở: - Em chết mất anh ơi, bọc nước bể rồi, em không còn đi được nữa, chắc em phải sanh rớt ở đây quá. Tôi thật sự kinh hoàng khi nghe Hồng nói câu đó. Phản xạ tự nhiên, tôi bật dậy, chạy ngược lại xóm cạnh bờ sông, kêu cứu: - Thím chín ơi, thím tám ơi, có ai ở đây không, cứu giùm vợ tôi với. Bớ bà con cô bác ơi, có ai ở nhà không, cứu giùm vợ tôi với. Cừa ngõ nhà Chín Thắng đóng chặt, nhà xa cửa ngõ quá, tôi không chắc trong nhà nghe tiếng tôi kêu cứu. .. Giọng tôi lạc đi, tôi chạy cuống quýt, bất chấp bờ bụi, tăm tối. .. Tôi càn đại xuống sông, bơi sang bờ bên kia, như vậy còn nhanh hơn phải qua cái cầu khỉ lung lay kia. .. Tôi trườn mình trên bãi bùn, ào lên bờ, đâp cửa nhà chú tám Liễu: - Chú Tám, thím tám ơi, có nhà không, làm ơn cứu giùm vợ cháu với! - Thày giáo hả? chuyện gì vậy? - Vợ cháu đau bụng đẻ, tính đi nhà thương - giọng tôi run rẩy vì lạnh và sợ - không dè đến đây nước ối bị bể rồi, đi không kịp, chú thím giúp giùm nhờ thằng Hai con chú chèo ghe chở giùm vợ cháu ra y tế xã. .. Tiếng mở cửa lịch kịch, thím tám bước ra: - Khổ gì mà khổ dữ vậy, cô giáo đang ở đâu? Thằng Hai lấy ghe đi Minh Hải hai ngày nay rồi - Dạ, qua bên kia sông rồi. Bác Tư Thuận, anh chú Tám Liễu cũng bước ra: - Năm thày giáo lấy xuồng của tao chở nó ra xã mau, mưa gió thế này, đẻ ngoài đường, chết mất. Tiếng Hai Câu, con trai chú nói vọng từ trong nhà ra cản: - Không được đâu, tía! cổ mà đẻ rớt trên xuồng, tui quăng xuồng luôn, làm ăn gì được nữa? - Thày giáo thông cảm, xuồng tui đi giăng câu kiếm sống đó. hay là thày chạy xuống chú Tám Lính mượn xuồng nhỏ của chú, xuồng ổng dể làm chưn đi trong mùa nước nổi, không có làm ăn gì đâu! - Bây giờ đi ra xã cũng không kịp, thím tám nói chen vào, mà chắc gì y tá có ở đó, mưa gió đêm hôm thế này, đâu có ai ở đó! bọc nước bể rồi, nó sanh bây giờ, thày giáo chạy xuống kêu bà Ba Thợ mộc, ngày trước bả là mụ vườn đó, mau đi chớ không kịp, tui với chị tư qua đó trước, cổ nằm chỗ nào? - Dạ, cạnh gốc xoài ở cuối vườn bà Tư Thỏ Nói xong, tôi lập cập chạy xuống nhà bà Ba Thợ mộc. .. Lúc tôi đâm được xuồng vào bờ, tóm vội dây xuồng vào cọc chiếc cầu khỉ nền bót, nhảy lên bờ thì đã thấy ánh của năm ba chiêc đèn lồng chỗ Hồng ngồi và tiếng cười nói lao xao của mấy bà. Tôi hỏi lớn: - Sao rồi thím Tám? - Cổ sanh rồi, thày giáo ơi, con gái. .. Nỗi mệt nhọc tan biến gần như tức khắc, tôi hỏi tiếp: - Nhau ra chưa? - Chưa, tiếng bà Ba Thợ mộc, để đó tao lo, chút xíu nữa là xong. .. Tôi đi lần tới, không còn cảm thấy lo sợ, mệt nhọc, lạnh lẽo. Tiếng Hai Đông: - Thày giáo, nghe mấy bả lao xao, tui ra coi thử. .. vợ tui phụ với mấy bả ở đẳng, lúc nghe thím tám la &quot; con nhỏ xổ rồi&quot; , tui coi đồng hồ, nó lọt lòng lúc 1 giờ 57 sáng, tui chờ để nói cho thày hay! - Ô, cám ơn anh hai nhiều lắm. - Tụi mình mà, tui cũng như thày giáo thôi, ơn nghĩa gì mà thày nói. Mình đàn ông, lại đó không tiện, ngồi đây chờ coi có gì tiếp cứu. Nhau ra rồi! Cầm lá nhau trơn tuột, tôi quan sát kỹ dưới ánh đèn dầu, nhau tróc đều. .. tôi yên tâm. Những năm tháng biến động của Mậu Thân ngày trước, một lần trực phòng y tế của trạm tiếp cư nạn nhân chiến tranh với một sinh viên y khoa, tôi đã phảu làm phụ tá bất đắc dĩ trong một ca đẻ tại trại vì giới nghiêm toàn thành phố, không có cách gì chở sản phụ đi nhà thương được; anh bạn y khoa đã chỉ cho tôi coi hình dạng và tình trạng lá nhau của sản phụ để có thể đoán coi nhau còn sót hay không. - Bây giờ êm rồi, tiếng thím Chín Thắng, thày giáo phụ đưa cổ xuống xuồng. - Nếu không còn gì nguy hiểm cháu muốn đưa vợ cháu về nhà, còn hai đứa nhỏ ở nhà một mình. .. - Vậy thì mau lên, bà Ba Thợ mộc nói, để lâu quá không nên, về lẹ kiếm củi đốt xông cho ấm, để lâu, hàn nhập lý, cổ không chết sau này cũng bịnh rề rề, còn khổ nữa. .. sẵn tụi tui cũng phải qua sông, phụ kéo xuồng qua mặt đập, rồi thày giáo chống riết trên ruộng về nhà. Mây lại kéo tới úp chụp trên đầu, trời tối như bưng mắt, nhìn không quá hai thước qua ánh đèn lồng trước để trên mũi xuồng. Hồng nằm dài trên tấm ván xuồng gồ ghề nứt nẻ, dưới tấm ny lông và mớ quần áo ướt át, con nhỏ được quấn trong chiêc khăn lông nằm trong tay mẹ nó. Tôi quặc tay giầm, móc cho mũi xuồng hướng vào mặt đập. Xạc! mũi xuồng gối lên đám lục bình dày đặc trước đập, xuồng chòng chành, chiếc đèn lồng rơi xuống sông, tôi cảm thấy ướt chỗ ván ngồi: &quot; chết cha! - tôi nghĩ nhanh - nước vô xuồng. .. &quot; tôi tụt nhanh xuống sông, hai tay nâng, đẩy nhanh xuồng vào mặt đập. Tiếng Hồng kêu lên: - Anh! anh! , nước vô xuồng! - Anh biết rồi, em bình tỉnh, không sao đâu, tôi trấn an Hồng đã ngồi dậy trong xuồng, lưng ướt đẫm, tay đỡ con nhỏ nâng lên cao. Tôi đứng nước mấp mé vai, gồng sức nâng xuồng lên cao. .. - Chèng ơi! - thím Tám Liễu kêu lên - gì nữa đây? - Dạ, nước vô xuồng, thím tám ơi, Hồng nói. - Chết chớ phải chơi sao, bà Ba Thợ mộc la lên, mau phụ kéo nó lên bờ mau. Có sao không cô giáo? - Cháu không sao, chỉ bị ướt hết lưng, tiếng Hồng run run. - Chèng đét, mới sanh xong đã bị ướt mà còn nói không sao. Thôi bây giờ tím Tám cầm đèn đi trước, thày giáo cõng cô giáo theo sau, tụi tui ôm đồ theo sau hết. Thày giáo nhớ, mệt thì nghỉ, để trợt té là cổ chết luôn. &quot; Té là chết luôn, té là chết luôn. .. &quot; cõng Hồng trên lưng mà câu nói của bá Ba thợ mộc cứ vang vang trong tai, &quot; Té là chết luôn, té là chết luôn. .. &quot; Đường trơn như mỡ, sức nặng trên lưng, tôi lặt lè bấm chân bước từng bước một &quot; Té là chết luôn, té là chết luôn. .. &quot; Tôi cảm thấy như có giòng nước ấm chảy dài trên lưng &quot; Té là chết luôn, té là chết luôn. .. &quot; Chỉ còn chừng hơn trăm thước nữa là đến nhà, trời lại bắt đầu lắc rắc, tiếng sấm gầm gừ từ xa, ánh chớp loang loáng. .. có tiếng thím tám phía trước: - Mau lên thày giáo, cô giáo trúng cơn mưa này là không xong đâu. .. ông Trời à! làm ơn chờ vợ chồng nó về tới nhà rồi hẵng mưa. .. Ráng chút lên thày giáo! Tôi bậm miệng bước tới, bước tới. .. không còn cảm giác nào khác, cứ bước tới. .. bước tới. .. bước tới. .. Sấm nổ ầm ầm, chớp lóe loang loáng, hàng trâm bầu vật vã vì gió. .. Vừa lúc đặt được Hồng xuống giường thì mưa gió ập tới; mấy bà, người phụ thay quần áo khô cho Hồng, người lo nhúm lửa hơ. .. - Coi chừng có củi giá không, khói củi giá độc lắm, sưng mình mẩy chết, bà Ba Thợ mộc nói. - Con nhỏ chết lạnh bây giờ không sợ, lại sợ khói, thím Tám Liễu đáp, chèng ơi củi gì mà ướt mem, chừng nào mới cháy đây. Tôi rút vội mấy cuốn sách trên kệ gỗ tạp đóng sơ sài, không kịp nhìn đó là sách gì: - Thím cứ lấy đốt, không có củi giá đâu, trâm bầu đó, nóng một chút chảy nhựa là cháy ngay. Mùi dầu gió xông nồng nặc, tiếng bà Ba Thợ mộc nói &quot; thím chín chà mạnh tay lên chỗ ngực và bụng của nó cho ấm&quot; Mưa gió dập đùng đùng vào vách lá, tôi phải chạy vội ra ngoài, cột lại tấm ny lông và che thêm nửa tấm lều vải cá nhân còn sót lại từ hồi đi Thủ Đức chổ giường nằm cho khỏi bị tạt mưa và kín gió. Hai đứa nhỏ cũng thức dậy, ngồi thu lu trong góc giường của chúng nhìn người lớn lăng xăng quanh mẹ nó * * * Mưa dịu lần, lửa cũng đã bén cháy, mùi khói tỏa ấm trong nhà, mẹ con sản phụ cũng nằm yên, hai thằng con đang tò mò ngắm nhìn em bé còn đỏ hõn quấn gọn trong chiếc khăn lông. Tôi nấu ấm nước, pha bình nước nóng, mời mấy bà. Thím Chín Thắng kể lại: &quot; Lúc nghe tiếng kêu, má tôi nói, tiếng ai tuồng như tiếng Năm Thày Giáo, bây ra thử coi. Tui ra không thấy ai, bên kia, vơ Hai Đông cũng cầm đèn bước ra hỏi, gì vậy thím chín? - hổng biết, tuồng như có ai kêu cứu - cháu cũng nghe như vậy. Hai đứa tôi bước hẳn ra bờ ngó lên ngó xuống thì thấy ánh đèn lồng chỗ cô giáo. Tụi tôi bước tới thì chèng ơi, con nhỏ xổ rồi, cô giáo đang hai tay bụm đứa nhỏ. Tôi la làng, má tôi chạy vô nhà lôi chiếc chiếu. .. Thím Tám Liễu chen vô: lúc đó tui với chị tư đang ở bên kia cầu chờ bà Ba, trời mưa đường trơn đêm hôm qua cái cầu khỉ đó, nói thiệt, cũng ớn, nghe chị kêu, hai chị em phang qua. .. kế bà ba tới cắt rún cho con nhỏ bằng con dao ăn trầu của bà Tư má Chín Thắng Trời hửng sáng, mưa cũng ngưng rớt hột, mấy bà kiếu từ ra về, tôi cũng thu xếp trở ra mặt đập, thu gọn quần áo của Hồng và nhau của con nhỏ đem về. Tôi nói với Hồng tôi phải ra lắc rửa, trả xuồng rồi ra chợ kiếm ít tiền mua gạo. Lúc trả xuồng, chú Tám Lính hỏi thăm, tôi kể lại chuyện, chú chép miệng: - Thôi, mọi chuyện qua được là may rồi, tôi có mớ ớt bị ngập nước, mới hái chiều hôm qua, định sáng nay đem chợ bán. Thày giáo mang

# Tokenize

In [14]:
SEED = 42
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

BOS, EOS, PAD, UNK, PARA = "<BOS>", "<EOS>", "<PAD>", "<UNK>", "<PARA>"

In [15]:
import re, unicodedata

class Tokenizer:
    def __init__(self, specials: List[str] = [BOS, EOS, PARA]):
        esc = [re.escape(s) for s in specials]
        specials_pat = "|".join(esc)
        self.tok_re = re.compile(
            rf"({specials_pat}|\.\.\.|…|[.,!?;:()\[\]\"'“”‘’—-]|[\w\-]+)",
            flags=re.UNICODE
        )

    def tokenize(self, s: str) -> List[str]:
        s = unicodedata.normalize("NFC", s or "")
        return [t for t in self.tok_re.findall(s) if t.strip()]

In [16]:
tokenizer = Tokenizer()
tokenizer.tokenize(train_records[0])[:50]

['<BOS>',
 'Hòa',
 'Đa',
 'Sanh',
 'Rớt',
 'Thời',
 'gian',
 'gặp',
 'lại',
 'vợ',
 'con',
 ',',
 'sau',
 'khi',
 'học',
 'cải',
 'tạo',
 'cũng',
 'qua',
 'mau',
 'Ngày',
 'tháng',
 'cứ',
 'dần',
 'trôi',
 'mà',
 'tôi',
 'không',
 'biết',
 'phải',
 'làm',
 'gì',
 'hơn',
 'là',
 'cứ',
 'quanh',
 'quẩn',
 'trông',
 'chừng',
 'hai',
 'đứa',
 'nhỏ',
 ',',
 'giúp',
 'vợ',
 'rảnh',
 'tay',
 'ngược',
 'xuôi',
 ',']

# Build Vocab

In [18]:
class Vocab:
    def __init__(self, min_freq = 2, max_size = 60000):
        self.min_freq = min_freq
        self.max_size = max_size
        self.stoi: Dict[str, int] = {}
        self.itos: Dict[int, str] = {}

    def build(self, texts: Iterable[str], tokenizer: Tokenizer):
        counter = Counter()
        for s in texts:
            counter.update(tokenizer.tokenize(s))

        # đảm bảo token đặc biệt lên đầu
        specials = [PAD, UNK, BOS, EOS, PARA]
        for sp in specials:
            counter[sp] += 10**9

        vocab = [w for w, c in counter.items() if c >= (0 if w in specials else self.min_freq)]
        vocab.sort(key=lambda w: (-counter[w], w))
        if self.max_size:
            vocab = vocab[:self.max_size]

        self.stoi = {w: i for i, w in enumerate(vocab)}
        self.itos = {i: w for w, i in self.stoi.items()}

    def __len__(self):
        return len(self.stoi)

    def encode(self, tokens: List[str]) -> List[int]:
        unk = self.stoi.get(UNK, None)
        return [self.stoi.get(t, unk) for t in tokens]

    def decode(self, ids: List[int]) -> List[str]:
        return [self.itos.get(i, UNK) for i in ids]

    def save(self, path: str):
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"stoi": self.stoi, "itos": self.itos}, f, ensure_ascii=False)

    @staticmethod
    def load(path: str) -> "Vocab":
        with open(path, "r", encoding="utf-8") as f:
            obj = json.load(f)
        v = Vocab()
        v.stoi = {k: int(v_) if isinstance(v_, str) and v_.isdigit() else v_ for k, v_ in obj["stoi"].items()}
        v.itos = {int(k): v_ for k, v_ in obj["itos"].items()}
        return v

In [19]:
tokenizer = Tokenizer()

# build vocab
vocab = Vocab(max_size=50000, min_freq=1)
vocab.build(train_records, tokenizer)

In [43]:
print("Number of words in vocab:", len(vocab))
print("20 samples:", list(vocab.stoi.keys())[:20])

Number of words in vocab: 50000
20 samples: ['<BOS>', '<EOS>', '<PAD>', '<PARA>', '<UNK>', ',', '.', 'không', '-', 'một', 'có', 'là', 'của', ':', 'người', 'và', 'nói', 'đã', '?', 'lại', 'tôi', 'cho', 'ra', 'được', 'như', 'ta', 'đi', ';', 'trong', 'anh', '!', 'cũng', 'với', 'đến', 'mà', 'thì', 'phải', 'làm', 'những', 'vào', 'đó', 'con', '"', 'này', 'rồi', 'quot', 'lên', 'gì', 'để', 'ở']

In [22]:
tokens = tokenizer.tokenize("<BOS> Ronaldoooo Ronaldo ghi bàn thắng tiếp theo, đưa đội nhà dành chiến thắng ngược dòng. <EOS>")
ids = vocab.encode(tokens)
print(ids)
print(vocab.decode(ids))

[0, 4, 41060, 1278, 251, 871, 182, 118, 5, 179, 577, 70, 1217, 332, 871, 1114, 989, 6, 1]
['<BOS>', '<UNK>', 'Ronaldo', 'ghi', 'bàn', 'thắng', 'tiếp', 'theo', ',', 'đưa', 'đội', 'nhà', 'dành', 'chiến', 'thắng', 'ngược', 'dòng', '.', '<EOS>']

# Dataset and Dataloader

In [30]:
class LMDataset(Dataset):
    def __init__(self, records: List[str], tokenizer, vocab, max_len: int = 256, stride: Optional[int] = None, drop_last_short: bool = True):
        self.vocab = vocab
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.stride = stride or max_len
        self.samples: List[List[int]] = []

        for s in records:
            ids = vocab.encode(tokenizer.tokenize(s))
            # trượt cửa sổ theo stride
            for i in range(0, max(0, len(ids) - 1), self.stride):
                chunk = ids[i:i + max_len]
                if drop_last_short and len(chunk) < 4:
                    continue
                if len(chunk) >= 2:
                    self.samples.append(chunk)

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx) -> Tuple[torch.Tensor, torch.Tensor]:
        seq = self.samples[idx]
        x = torch.tensor(seq[:-1], dtype=torch.long)
        y = torch.tensor(seq[1:],  dtype=torch.long)
        return x, y

def lm_collate(batch, pad_id: int):
    seqs, ys = zip(*batch)
    padded_x = pad_sequence(seqs, batch_first=True, padding_value=pad_id)
    padded_y = pad_sequence(ys,   batch_first=True, padding_value=pad_id)
    mask     = (padded_x != pad_id).long()
    return padded_x, padded_y, mask

In [53]:
pad_id = vocab.stoi["<PAD>"]
train_ds = LMDataset(train_records, tokenizer, vocab, max_len=128)
val_ds   = LMDataset(val_records,   tokenizer, vocab, max_len=128)
test_ds  = LMDataset(test_records,  tokenizer, vocab, max_len=128)

In [54]:
collate = partial(lm_collate, pad_id=pad_id)
train_loader = DataLoader(train_ds, batch_size=32, shuffle=True,  collate_fn=collate)
val_loader   = DataLoader(val_ds,   batch_size=32, shuffle=False, collate_fn=collate)
test_loader  = DataLoader(test_ds,  batch_size=32, shuffle=False, collate_fn=collate)

xb, yb, mask = next(iter(train_loader))
print(xb.shape, yb.shape, mask.shape)

torch.Size([32, 127]) torch.Size([32, 127]) torch.Size([32, 127])

# Build Model

In [46]:
class LSTMLM(nn.Module):
    def __init__(self, vocab_size, emb_dim=256, hidden_dim=384, num_layers=2, pad_id=0, dropout=0.3):
        super().__init__()
        self.embed = nn.Embedding(vocab_size, emb_dim, padding_idx=pad_id)
        self.lstm  = nn.LSTM(emb_dim, hidden_dim, num_layers=num_layers,
                             batch_first=True, dropout=dropout)
        self.drop  = nn.Dropout(dropout)
        self.fc    = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x, h=None):
        emb = self.embed(x)
        out, h = self.lstm(emb, h)
        out = self.drop(out)
        logits = self.fc(out)  # [B, T, V]
        return logits, h

In [47]:
pad_id = vocab.stoi["<PAD>"] 
model = LSTMLM(vocab_size=len(vocab), pad_id=pad_id)
print(model)

LSTMLM(
  (embed): Embedding(50000, 256, padding_idx=2)
  (lstm): LSTM(256, 384, num_layers=2, batch_first=True, dropout=0.3)
  (drop): Dropout(p=0.3, inplace=False)
  (fc): Linear(in_features=384, out_features=50000, bias=True)
)

In [48]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total params: {total_params:,}")

Total params: 34,218,832

# Train

In [61]:
class LMTrainer:
    def __init__(
        self,
        model: nn.Module,
        pad_id: int,
        device: str = "cpu",
        lr: float = 3e-4,
        weight_decay: float = 0.01,
        use_scheduler: bool = True,
        amp: bool = True,             
        accum_steps: int = 1          
    ):
        self.model = model.to(device)
        self.pad_id = pad_id
        self.device = device
        self.amp = amp and torch.cuda.is_available()
        self.accum_steps = max(1, accum_steps)

        self.criterion = nn.CrossEntropyLoss(ignore_index=pad_id)
        self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=lr, weight_decay=weight_decay)
        self.scheduler = (
            torch.optim.lr_scheduler.ReduceLROnPlateau(self.optimizer, mode="min", factor=0.5, patience=1)
            if use_scheduler else None
        )
        self.scaler = torch.cuda.amp.GradScaler(enabled=self.amp)

        self.history = {"train_loss": [], "val_loss": [], "train_ppl": [], "val_ppl": []}

    def _forward_loss(self, xb, yb):
        logits, _ = self.model(xb)  # [B,T,V]
        loss = self.criterion(logits.reshape(-1, logits.size(-1)), yb.reshape(-1))
        return loss, logits

    @torch.no_grad()
    def evaluate(self, loader):
        self.model.eval()
        total_loss, total_tok = 0.0, 0
        pbar = tqdm(loader, desc="Valid", leave=False)
        for xb, yb, mask in pbar:
            xb, yb, mask = xb.to(self.device), yb.to(self.device), mask.to(self.device)
            loss, _ = self._forward_loss(xb, yb)
            ntok = mask.sum().item()
            total_loss += loss.item() * ntok
            total_tok  += ntok
            avg_loss = total_loss / max(total_tok, 1)
            pbar.set_postfix(loss=f"{avg_loss:.4f}", ppl=f"{math.exp(avg_loss):.2f}")
        avg_loss = total_loss / max(total_tok, 1)
        ppl = math.exp(avg_loss)
        return avg_loss, ppl

    def train_one_epoch(self, loader, grad_clip=1.0, epoch_idx=1, epochs=1):
        self.model.train()
        total_loss, total_tok = 0.0, 0
        step = 0

        pbar = tqdm(loader, desc=f"Epoch {epoch_idx}/{epochs}", leave=True)
        autocast_ctx = torch.cuda.amp.autocast if self.amp else nullcontext

        self.optimizer.zero_grad(set_to_none=True)

        for xb, yb, mask in pbar:
            xb, yb, mask = xb.to(self.device), yb.to(self.device), mask.to(self.device)
            with autocast_ctx():
                loss, _ = self._forward_loss(xb, yb)
                loss_to_backprop = loss / self.accum_steps

            # backward (AMP)
            if self.amp:
                self.scaler.scale(loss_to_backprop).backward()
            else:
                loss_to_backprop.backward()

            step += 1
            do_step = (step % self.accum_steps == 0)

            if do_step:
                if grad_clip is not None:
                    if self.amp:
                        self.scaler.unscale_(self.optimizer)
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), grad_clip)

                if self.amp:
                    self.scaler.step(self.optimizer)
                    self.scaler.update()
                else:
                    self.optimizer.step()

                self.optimizer.zero_grad(set_to_none=True)

            # logging tiến trình
            ntok = mask.sum().item()
            total_loss += loss.item() * ntok
            total_tok  += ntok
            avg_loss = total_loss / max(total_tok, 1)
            ppl = math.exp(avg_loss)

            # thông tin thêm: LR + (tuỳ) bộ nhớ GPU
            lr = self.optimizer.param_groups[0]["lr"]
            postfix = dict(loss=f"{avg_loss:.4f}", ppl=f"{ppl:.2f}", lr=f"{lr:.2e}")
            if torch.cuda.is_available() and self.device.startswith("cuda"):
                free, total = torch.cuda.mem_get_info()
                used_gb = (total - free) / (1024**3)
                postfix["gpu_used"] = f"{used_gb:.1f}G"
            pbar.set_postfix(postfix)

        avg_loss = total_loss / max(total_tok, 1)
        ppl = math.exp(avg_loss)
        return avg_loss, ppl

    def fit(self, train_loader, val_loader, epochs=6, ckpt_path="lstm_lm.pt", grad_clip=1.0, patience=2):
        best_val = float("inf")
        bad_epochs = 0

        for ep in range(1, epochs + 1):
            tr_loss, tr_ppl = self.train_one_epoch(train_loader, grad_clip=grad_clip, epoch_idx=ep, epochs=epochs)
            va_loss, va_ppl = self.evaluate(val_loader)

            self.history["train_loss"].append(tr_loss)
            self.history["val_loss"].append(va_loss)
            self.history["train_ppl"].append(tr_ppl)
            self.history["val_ppl"].append(va_ppl)

            print(f"Epoch {ep:02d} | Train PPL: {tr_ppl:.2f} | Val PPL: {va_ppl:.2f}")

            if self.scheduler:
                self.scheduler.step(va_loss)

            if va_ppl < best_val:
                best_val = va_ppl
                torch.save({"model": self.model.state_dict()}, ckpt_path)
                bad_epochs = 0
                print("  -> Saved best model")
            else:
                bad_epochs += 1
                if bad_epochs >= patience:
                    print(f"Early stopping at epoch {ep} (no improvement for {patience} epochs).")
                    break

    def test(self, test_loader, ckpt_path="lstm_lm.pt"):
        ckpt = torch.load(ckpt_path, map_location=self.device)
        self.model.load_state_dict(ckpt["model"])
        test_loss, test_ppl = self.evaluate(test_loader)
        print(f"Test PPL: {test_ppl:.2f}")
        return test_loss, test_ppl

In [56]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DEVICE

'cuda'

In [62]:
pad_id = vocab.stoi["<PAD>"]

model = LSTMLM(vocab_size=len(vocab), emb_dim=256, hidden_dim=384, num_layers=2, pad_id=pad_id, dropout=0.3)

trainer = LMTrainer(
    model, pad_id=pad_id, device=DEVICE,
    lr=3e-4, weight_decay=0.01,
    amp=True,          
    accum_steps=2        
)

trainer.fit(train_loader, val_loader, epochs=2, ckpt_path="lstm_lm.pt", grad_clip=1.0, patience=2)
trainer.test(test_loader, ckpt_path="lstm_lm.pt")

/tmp/ipykernel_37/1425706927.py:25: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.scaler = torch.cuda.amp.GradScaler(enabled=self.amp)
Epoch 1/5:   0%|          | 0/57028 [00:00<?, ?it/s]/tmp/ipykernel_37/1425706927.py:63: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with autocast_ctx():
Epoch 1/5:   0%|          | 124/57028 [00:13<1:46:22,  8.92it/s, loss=8.3792, ppl=4355.38, lr=3.00e-04, gpu_used=14.8G]

KeyboardInterrupt: